version: "3"

services:
  ui:
    container_name: expense-tracker-ui
    restart: always
    build: ./ui
    volumes:
      - "./ui:/app"
      - "/app/node_modules"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  api:
    container_name: expense-tracker-api
    restart: always
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - "8080:8080"
    external_links:
      - mongo
    env_file:
      - ./api/.env
    command: yarn dev

  mongo:
    container_name: expense-tracker-db
    image: mongo
    ports:
      - "27017:27017"
